artifacts:
  ARTIFACTS_DIR: artifacts
  DETECTRON2_URL: 'git+https://github.com/facebookresearch/detectron2.git'
  TRAIN_URL: '1lQZOIkO-9L0QJuk_w1K8-tRuyno-KvLK'
  TEST_URL: '1hsa-UE-LX8sks8eAcGLL-9QDNyNt6VgP'
  VALIDATION_URL: '1O45YqhREBOoLudjA06HcTehcEebR0o9y'
  JSON_FOR_VAL_URL: '12DmrxXNtl0U9hnN1bzue4XX7nw1fSMZ5'
  MODEL_URL: 'COCO-Detection/faster_rcnn_R_101_FPN_3x.yaml'
  # MODEL_URL: 'COCO-Detection/fast_rcnn_R_50_FPN_1x.yaml'

paths:
  WORKSPACE_PATH : workspace
  IMAGE_PATH : images
  OUTPUT_PATH : output

params:
  IMS_PER_BATCH : 4
  BASE_LR : 0.001
  WARMUP_ITERS : 1000
  MAX_ITER : 1500
  STEPS : 
    - 1000
    - 1500
  GAMMA : 0.05
  BATCH_SIZE_PER_IMAGE : 64
  NUM_CLASSES : 13
  EVAL_PERIOD : 500
  SCORE_THRESH_TEST : 0.05


