CONFIG_FILE_NAME = "config.yaml"

ARTIFACTS_KEY = "artifacts"
ARTIFACTS_DIR = "ARTIFACTS_DIR"

PATH_KEY = "paths"
DETECTRON2_URL = "DETECTRON2_URL"
WORKSPACE_NAME = "WORKSPACE_PATH"
SCRIPTS_NAME = "SCRIPTS_PATH"
IMAGE_PATH = "IMAGE_PATH"